title: 2. Поставщики данных
optionalCategoryIndex: true
supportedLanguages:
  - ru
language: ru
properties: []
description: Настройка подключения к брокерам и биржам
style: green-orange
group: tslab
order: 2
